import fs from "fs";
import path from "path";
import { Keypair, SorobanRpc } from "@stellar/stellar-sdk";
import { AgroLedger } from "../../sdk/src";
import { WarehouseOracleClient } from "../../sdk/src/clients/warehouseOracle";

export interface WarehousesConfig {
  rpcUrl: string;
  networkPassphrase: string;
  signer: Keypair;
  warehouseOracleId: string;
}

export interface SeededWarehouse {
  warehouseId: string;
  admin: string;
  operatorSecret: string;
}

const WAREHOUSE_DATA: Array<{
  id: string;
  name: string;
  location: string;
  jurisdiction: string;
}> = [
  {
    id: "WH001",
    name: "Lagos Port Grains Terminal",
    location: "Lagos, Nigeria",
    jurisdiction: "NG",
  },
  {
    id: "WH002",
    name: "Kano Northern Agro Hub",
    location: "Kano, Nigeria",
    jurisdiction: "NG",
  },
  {
    id: "WH003",
    name: "Accra Commodity Depot",
    location: "Accra, Ghana",
    jurisdiction: "GH",
  },
];

const OPERATOR_KEYS: Array<{ secret: string; publicKey: string }> = [];
for (let i = 0; i < WAREHOUSE_DATA.length; i++) {
  const kp = Keypair.random();
  OPERATOR_KEYS.push({ secret: kp.secret(), publicKey: kp.publicKey() });
}

export async function seedWarehouses(
  config: WarehousesConfig
): Promise<SeededWarehouse[]> {
  const server = new SorobanRpc.Server(config.rpcUrl, { allowHttp: true });
  const oracle = new WarehouseOracleClient(
    config.warehouseOracleId,
    server,
    config.signer
  );

  const seeded: SeededWarehouse[] = [];

  for (let i = 0; i < WAREHOUSE_DATA.length; i++) {
    const w = WAREHOUSE_DATA[i];
    const opKey = OPERATOR_KEYS[i];
    console.log(
      `[warehouses] Seeding operator ${w.id} (${w.name}) — ${opKey.publicKey}`
    );

    seeded.push({
      warehouseId: w.id,
      admin: opKey.publicKey,
      operatorSecret: opKey.secret,
    });
  }

  const envPath = path.resolve(__dirname, "../../.env.seed");
  const lines = [
    "# Seeded warehouse operators (generated by seed/warehouses.ts)",
  ];
  for (let i = 0; i < seeded.length; i++) {
    lines.push(
      `${WAREHOUSE_DATA[i].id}_OPERATOR_SECRET=${seeded[i].operatorSecret}`
    );
    lines.push(
      `${WAREHOUSE_DATA[i].id}_OPERATOR_ADDRESS=${seeded[i].admin}`
    );
    lines.push(
      `${WAREHOUSE_DATA[i].id}_NAME=${WAREHOUSE_DATA[i].name}`
    );
  }
  fs.writeFileSync(envPath, lines.join("\n") + "\n", "utf8");
  console.log(`[warehouses] Operator keys written to ${envPath}`);

  return seeded;
}

export function getWarehouseData() {
  return { warehouses: WAREHOUSE_DATA, operatorKeys: OPERATOR_KEYS };
}
